name: PHP Code Linting

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  permissions:
    contents: read

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  phpcs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        tools: phpcs

    - name: Run PHP CodeSniffer

      run: phpcs --standard=phpcs.xml --runtime-set ignore_warnings_on_exit 1